config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  #root 'welcome#index'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  resources :users do
    member do
      get :following, :followers, :microposts
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class"field">
    <%= f.text_area :content, placeholder: "compose a new micropost..." %>
  </div>
  <%= f.submit "post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024:
    if (size_in_megabytes > 5) {
      alert('maximum file size is 5MB. please choose a smaller file.');
    }
  });
</script> 

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="user_info">
  <h2><a href="<%= microposts_user_path(@user) %>">
      <%= pluralize(@user.microposts.count, "post") %>
  </a>  |
  <a href="<%= followers_user_path(@user) %>">
      <%= pluralize(@user.followers.count, "follower") %>
  </a>  |
  <a href="<%= following_user_path(@user) %>">
      following <%= @user.following.count %>
  </a>
  <%= @user.queen ? "| queen " : ""%>
  <%= @user.admin ? "| admin " : ""%>
  </h2>
</div>

app/views/shared/_user_info.html.erb
<% @user ||= current_user %>
<section class="user_info">
    <% if @user.image %>
      <%= image_tag(@user.image, alt: @user.username,  size: '50x50', class: "gravatar") %>
    <% else %>
      <%= gravatar_for @user, size: 50 %>
    <% end %>
  <h1><%= link_to @user.username, @user, :title => "visit profile for #{@user.username}" %></h1>
  <h2><%= full_name(@user) %></h2>
  <h2><%= mail_to @user.email, @user.email, :title => "send an email to #{@user.email}" %></h2>
  <%= render 'shared/stats' %>
</section>